In [1]:
import pandas as pd

url = "https://raw.githubusercontent.com/jbrownlee/Datasets/master/airline-passengers.csv"
df = pd.read_csv(url, parse_dates=['Month'], index_col='Month')

print(df.head())

            Passengers
Month
1949-01-01         112
1949-02-01         118
1949-03-01         132
1949-04-01         129
1949-05-01         121

In [2]:
# Create lag features
df['lag1'] = df['Passengers'].shift(1)
df['lag2'] = df['Passengers'].shift(2)
df['lag3'] = df['Passengers'].shift(3)

# Rolling mean
df['rolling_mean'] = df['Passengers'].rolling(3).mean()

# Time features
df['month'] = df.index.month

# Drop missing values
df.dropna(inplace=True)

In [3]:
df

            Passengers   lag1   lag2   lag3  rolling_mean  month
Month
1949-04-01         129  132.0  118.0  112.0    126.333333      4
1949-05-01         121  129.0  132.0  118.0    127.333333      5
1949-06-01         135  121.0  129.0  132.0    128.333333      6
1949-07-01         148  135.0  121.0  129.0    134.666667      7
1949-08-01         148  148.0  135.0  121.0    143.666667      8
...                ...    ...    ...    ...           ...    ...
1960-08-01         606  622.0  535.0  472.0    587.666667      8
1960-09-01         508  606.0  622.0  535.0    578.666667      9
1960-10-01         461  508.0  606.0  622.0    525.000000     10
1960-11-01         390  461.0  508.0  606.0    453.000000     11
1960-12-01         432  390.0  461.0  508.0    427.666667     12

[141 rows x 6 columns]

In [4]:
train = df[:'1958']
test = df['1959':]

X_train = train.drop('Passengers', axis=1)
y_train = train['Passengers']

X_test = test.drop('Passengers', axis=1)
y_test = test['Passengers']

In [6]:
X_train

             lag1   lag2   lag3  rolling_mean  month
Month
1949-04-01  132.0  118.0  112.0    126.333333      4
1949-05-01  129.0  132.0  118.0    127.333333      5
1949-06-01  121.0  129.0  132.0    128.333333      6
1949-07-01  135.0  121.0  129.0    134.666667      7
1949-08-01  148.0  135.0  121.0    143.666667      8
...           ...    ...    ...           ...    ...
1958-08-01  491.0  435.0  363.0    477.000000      8
1958-09-01  505.0  491.0  435.0    466.666667      9
1958-10-01  404.0  505.0  491.0    422.666667     10
1958-11-01  359.0  404.0  505.0    357.666667     11
1958-12-01  310.0  359.0  404.0    335.333333     12

[117 rows x 5 columns]

In [7]:
X_test

             lag1   lag2   lag3  rolling_mean  month
Month
1959-01-01  337.0  310.0  359.0    335.666667      1
1959-02-01  360.0  337.0  310.0    346.333333      2
1959-03-01  342.0  360.0  337.0    369.333333      3
1959-04-01  406.0  342.0  360.0    381.333333      4
1959-05-01  396.0  406.0  342.0    407.333333      5
1959-06-01  420.0  396.0  406.0    429.333333      6
1959-07-01  472.0  420.0  396.0    480.000000      7
1959-08-01  548.0  472.0  420.0    526.333333      8
1959-09-01  559.0  548.0  472.0    523.333333      9
1959-10-01  463.0  559.0  548.0    476.333333     10
1959-11-01  407.0  463.0  559.0    410.666667     11
1959-12-01  362.0  407.0  463.0    391.333333     12
1960-01-01  405.0  362.0  407.0    394.666667      1
1960-02-01  417.0  405.0  362.0    404.333333      2
1960-03-01  391.0  417.0  405.0    409.000000      3
1960-04-01  419.0  391.0  417.0    423.666667      4
1960-05-01  461.0  419.0  391.0    450.666667      5
1960-06-01  472.0  461.0  419.0    489.333333      6
1960-07-01  535.0  472.0  461.0    543.000000      7
1960-08-01  622.0  535.0  472.0    587.666667      8
1960-09-01  606.0  622.0  535.0    578.666667      9
1960-10-01  508.0  606.0  622.0    525.000000     10
1960-11-01  461.0  508.0  606.0    453.000000     11
1960-12-01  390.0  461.0  508.0    427.666667     12

In [8]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error

rf = RandomForestRegressor(n_estimators=100)
rf.fit(X_train, y_train)

rf_pred = rf.predict(X_test)
print("RF RMSE:", mean_squared_error(y_test, rf_pred, squared=False))

RF RMSE: 65.08806985538901

C:\Users\PYTHON\anaconda3\Lib\site-packages\sklearn\metrics\_regression.py:483: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(

In [9]:
from xgboost import XGBRegressor

xgb = XGBRegressor(n_estimators=200, learning_rate=0.05)
xgb.fit(X_train, y_train)

xgb_pred = xgb.predict(X_test)

In [10]:
print("XGB RMSE:", mean_squared_error(y_test, xgb_pred, squared=False))

XGB RMSE: 77.41626418326746

C:\Users\PYTHON\anaconda3\Lib\site-packages\sklearn\metrics\_regression.py:483: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(